name: storekit_external_purchase_example
description: "Demonstrates how to use the storekit_external_purchase plugin."
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  storekit_external_purchase:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
