name: storekit_external_purchase
description: "Flutter plugin to use StoreKit External Purchase (custom link) APIs on Apple platforms. Provides eligibility check, capability check, and notice presentation. iOS only."
version: 0.0.1
homepage: 
repository: https://github.com/Ortes/storekit_external_purchase

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: StorekitExternalPurchasePlugin
